//! Face detection with SCRFD (Sample and Computation Redistribution Face Detector).
//!
//! Uses the InsightFace `det_10g.onnx` model which follows the SCRFD architecture:
//! - Input:  `input.1`  — `[1, 3, H, W]` float32, BGR, no mean subtraction
//! - Outputs: 9 tensors across 3 feature-map strides (8, 16, 32):
//!   - Per stride: `[N_i, 1]` scores, `[N_i, 4]` box deltas, `[N_i, 10]` keypoint deltas
//!
//! Output decoding follows the SCRFD reference implementation from InsightFace.
//! The public API (`DetectedFace`, `FaceDetector::detect`) is identical to the
//! previous RetinaFace implementation — zero changes required in callers.

use crate::CoreError;
use ndarray::Array4;
use ort::value::TensorRef;

// ─── Public types ─────────────────────────────────────────────────────────────

/// A detected face bounding box with keypoints.
#[derive(Debug, Clone)]
pub struct DetectedFace {
    /// Bounding box: `[x1, y1, x2, y2]` in pixels (original image coordinates).
    pub bbox: [f32; 4],
    /// Five facial keypoints: `[left_eye, right_eye, nose, left_mouth, right_mouth]`
    /// Each is `[x, y]` in pixels (original image coordinates).
    pub keypoints: [[f32; 2]; 5],
    /// Detection confidence score (0.0–1.0).
    pub score: f32,
}

// ─── FaceDetector ─────────────────────────────────────────────────────────────

/// Face detector using the InsightFace SCRFD `det_10g.onnx` model.
///
/// SCRFD is a highly efficient anchor-based face detector. The 10G variant
/// achieves state-of-the-art accuracy on WiderFace with ~10 GFLOPs at 640×640.
///
/// The model accepts dynamic spatial resolution via the `?×?` input shape —
/// we always feed 640×640 for maximum accuracy.
pub struct FaceDetector {
    session: ort::session::Session,
    /// Input resolution: (width, height).  SCRFD accepts any multiple of 32.
    input_size: (u32, u32),
}

impl FaceDetector {
    /// Create a new `FaceDetector` from a pre-loaded ONNX session.
    ///
    /// The `session` must correspond to `det_10g.onnx` (InsightFace SCRFD).
    #[must_use]
    pub fn new(session: ort::session::Session) -> Self {
        Self {
            session,
            input_size: (640, 640),
        }
    }

    /// Detect all faces in a frame.
    ///
    /// Returns faces sorted by confidence descending.
    /// Only returns faces with `score >= min_confidence`.
    ///
    /// `frame_rgb` must be `width * height * 3` packed RGB bytes, row-major.
    ///
    /// # Errors
    /// Returns [`CoreError::Inference`] on ONNX failure.
    /// Returns [`CoreError::Image`] if the RGB buffer size doesn't match `width × height`.
    pub fn detect(
        &mut self,
        frame_rgb: &[u8],
        width: u32,
        height: u32,
        min_confidence: f32,
    ) -> Result<Vec<DetectedFace>, CoreError> {
        let image =
            image::RgbImage::from_raw(width, height, frame_rgb.to_vec()).ok_or_else(|| {
                CoreError::Image(format!(
                    "RGB buffer length {} does not match {width}x{height}",
                    frame_rgb.len()
                ))
            })?;

        let (target_w, target_h) = self.input_size;

        // Scale factors: model-space → original-image-space
        let scale_x = width as f32 / target_w as f32;
        let scale_y = height as f32 / target_h as f32;

        // Preprocess: resize → BGR → NCHW f32
        let tensor = preprocess_scrfd(&image, self.input_size);
        let tensor_data = tensor
            .as_slice()
            .ok_or_else(|| CoreError::Inference("tensor non-contiguous".into()))?;

        let shape = [1_usize, 3, target_h as usize, target_w as usize];
        let tensor_ref = TensorRef::from_array_view((shape, tensor_data))
            .map_err(|e| CoreError::Inference(e.to_string()))?;

        // Run SCRFD inference — produces 9 output tensors
        let outputs = self
            .session
            .run(ort::inputs![tensor_ref])
            .map_err(|e| CoreError::Inference(e.to_string()))?;

        // SCRFD outputs 9 tensors in the following order for strides [8, 16, 32]:
        //   idx 0: scores stride-8  [N0, 1]
        //   idx 1: scores stride-16 [N1, 1]
        //   idx 2: scores stride-32 [N2, 1]
        //   idx 3: boxes  stride-8  [N0, 4]
        //   idx 4: boxes  stride-16 [N1, 4]
        //   idx 5: boxes  stride-32 [N2, 4]
        //   idx 6: kps    stride-8  [N0, 10]
        //   idx 7: kps    stride-16 [N1, 10]
        //   idx 8: kps    stride-32 [N2, 10]
        //
        // The actual numeric output names are auto-generated by ONNX (e.g. "448", "451"…)
        // but ort returns them in the order the graph exports them, which matches above.

        let strides = [8_u32, 16, 32];
        let mut candidates: Vec<DetectedFace> = Vec::new();

        for (level, &stride) in strides.iter().enumerate() {
            let scores_raw = outputs[level]
                .try_extract_array::<f32>()
                .map_err(|e| CoreError::Inference(e.to_string()))?;
            let boxes_raw = outputs[3 + level]
                .try_extract_array::<f32>()
                .map_err(|e| CoreError::Inference(e.to_string()))?;
            let kps_raw = outputs[6 + level]
                .try_extract_array::<f32>()
                .map_err(|e| CoreError::Inference(e.to_string()))?;

            let scores_flat = scores_raw.as_slice().unwrap_or(&[]);
            let boxes_flat = boxes_raw.as_slice().unwrap_or(&[]);
            let kps_flat = kps_raw.as_slice().unwrap_or(&[]);

            let n = scores_flat.len(); // one score per anchor

            // Generate anchor centers for this stride level
            let anchors = anchor_centers(target_w, target_h, stride);

            for i in 0..n {
                let score = sigmoid(scores_flat[i]);
                if score < min_confidence {
                    continue;
                }

                // Each anchor: (cx, cy) in model-space pixels
                let (acx, acy) = anchors[i];
                let s = stride as f32;

                // Box decoding: SCRFD predicts (left, top, right, bottom) distances
                // from the anchor center, scaled by stride.
                //   x1 = cx - left  * stride
                //   y1 = cy - top   * stride
                //   x2 = cx + right * stride
                //   y2 = cy + bottom* stride
                let left = boxes_flat[i * 4] * s;
                let top = boxes_flat[i * 4 + 1] * s;
                let right = boxes_flat[i * 4 + 2] * s;
                let bottom = boxes_flat[i * 4 + 3] * s;

                let x1 = ((acx - left) * scale_x).max(0.0);
                let y1 = ((acy - top) * scale_y).max(0.0);
                let x2 = ((acx + right) * scale_x).min(width as f32);
                let y2 = ((acy + bottom) * scale_y).min(height as f32);

                // Keypoint decoding: 5 points × 2 coords = 10 values per anchor
                // Each (dx, dy) offset is relative to anchor center, scaled by stride.
                let mut keypoints = [[0.0f32; 2]; 5];
                for k in 0..5 {
                    let dx = kps_flat[i * 10 + k * 2] * s;
                    let dy = kps_flat[i * 10 + k * 2 + 1] * s;
                    keypoints[k] = [(acx + dx) * scale_x, (acy + dy) * scale_y];
                }

                candidates.push(DetectedFace {
                    bbox: [x1, y1, x2, y2],
                    keypoints,
                    score,
                });
            }
        }

        // NMS + sort descending
        let mut faces = nms(candidates, 0.4);
        faces.sort_by(|a, b| {
            b.score
                .partial_cmp(&a.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        tracing::debug!(count = faces.len(), "faces detected (SCRFD)");

        Ok(faces)
    }
}

// ─── Preprocessing ────────────────────────────────────────────────────────────

/// Preprocess an RGB image for SCRFD inference.
///
/// Unlike RetinaFace, SCRFD does NOT use mean subtraction.
/// It expects BGR pixel values in `[0, 255]`, NCHW layout.
fn preprocess_scrfd(image: &image::RgbImage, target_size: (u32, u32)) -> Array4<f32> {
    let (target_w, target_h) = target_size;

    let resized = image::imageops::resize(
        image,
        target_w,
        target_h,
        image::imageops::FilterType::Triangle,
    );

    let mut tensor = Array4::<f32>::zeros((1, 3, target_h as usize, target_w as usize));
    for (x, y, pixel) in resized.enumerate_pixels() {
        let [r, g, b] = pixel.0;
        // SCRFD: BGR channel order, no mean subtraction, values in [0, 255]
        tensor[[0, 0, y as usize, x as usize]] = b as f32;
        tensor[[0, 1, y as usize, x as usize]] = g as f32;
        tensor[[0, 2, y as usize, x as usize]] = r as f32;
    }
    tensor
}

// ─── Anchor generation ────────────────────────────────────────────────────────

/// Generate anchor center coordinates for one stride level.
///
/// SCRFD uses 2 anchors per spatial location. For a 640×640 input:
/// - Stride 8  → 80×80 grid → 12800 anchors
/// - Stride 16 → 40×40 grid →  3200 anchors
/// - Stride 32 → 20×20 grid →   800 anchors
///
/// Returns `Vec<(cx, cy)>` in model-space pixels.
fn anchor_centers(input_w: u32, input_h: u32, stride: u32) -> Vec<(f32, f32)> {
    let feat_w = input_w / stride;
    let feat_h = input_h / stride;
    let num_anchors = 2; // SCRFD uses 2 anchors per location

    let mut centers = Vec::with_capacity((feat_w * feat_h * num_anchors) as usize);

    for gy in 0..feat_h {
        for gx in 0..feat_w {
            let cx = (gx as f32 + 0.5) * stride as f32;
            let cy = (gy as f32 + 0.5) * stride as f32;
            for _ in 0..num_anchors {
                centers.push((cx, cy));
            }
        }
    }

    centers
}

// ─── Utilities ────────────────────────────────────────────────────────────────

/// Sigmoid activation: maps raw logit to [0, 1] probability.
#[inline]
fn sigmoid(x: f32) -> f32 {
    1.0 / (1.0 + (-x).exp())
}

/// Compute IoU for two bounding boxes `[x1, y1, x2, y2]`.
fn iou(a: &[f32; 4], b: &[f32; 4]) -> f32 {
    let x1 = a[0].max(b[0]);
    let y1 = a[1].max(b[1]);
    let x2 = a[2].min(b[2]);
    let y2 = a[3].min(b[3]);

    let intersection = (x2 - x1).max(0.0) * (y2 - y1).max(0.0);
    if intersection == 0.0 {
        return 0.0;
    }
    let area_a = (a[2] - a[0]) * (a[3] - a[1]);
    let area_b = (b[2] - b[0]) * (b[3] - b[1]);
    intersection / (area_a + area_b - intersection)
}

/// Non-Maximum Suppression — removes overlapping detections.
fn nms(mut candidates: Vec<DetectedFace>, iou_threshold: f32) -> Vec<DetectedFace> {
    candidates.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let mut keep: Vec<DetectedFace> = Vec::new();
    'outer: for candidate in candidates {
        for kept in &keep {
            if iou(&candidate.bbox, &kept.bbox) > iou_threshold {
                continue 'outer;
            }
        }
        keep.push(candidate);
    }
    keep
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preprocess_scrfd_shape_is_correct() {
        let img = image::RgbImage::new(1920, 1080);
        let tensor = preprocess_scrfd(&img, (640, 640));
        assert_eq!(tensor.shape(), &[1, 3, 640, 640]);
    }

    #[test]
    fn preprocess_scrfd_bgr_no_mean_subtraction() {
        // Pure red pixel (R=255, G=0, B=0) in RGB
        // After RGB→BGR: C=0=B=0, C=1=G=0, C=2=R=255
        // No mean subtraction in SCRFD
        let mut img = image::RgbImage::new(1, 1);
        img.put_pixel(0, 0, image::Rgb([255, 0, 0]));
        let t = preprocess_scrfd(&img, (1, 1));
        assert!(
            (t[[0, 0, 0, 0]] - 0.0).abs() < 1e-5,
            "B channel: expected 0, got {}",
            t[[0, 0, 0, 0]]
        );
        assert!(
            (t[[0, 1, 0, 0]] - 0.0).abs() < 1e-5,
            "G channel: expected 0, got {}",
            t[[0, 1, 0, 0]]
        );
        assert!(
            (t[[0, 2, 0, 0]] - 255.0).abs() < 1e-5,
            "R channel: expected 255, got {}",
            t[[0, 2, 0, 0]]
        );
    }

    #[test]
    fn anchor_centers_stride8_count() {
        // 640/8 = 80 × 80 = 6400 locations × 2 anchors = 12800
        let centers = anchor_centers(640, 640, 8);
        assert_eq!(centers.len(), 12800);
    }

    #[test]
    fn anchor_centers_stride16_count() {
        // 640/16 = 40 × 40 = 1600 × 2 = 3200
        let centers = anchor_centers(640, 640, 16);
        assert_eq!(centers.len(), 3200);
    }

    #[test]
    fn anchor_centers_stride32_count() {
        // 640/32 = 20 × 20 = 400 × 2 = 800
        let centers = anchor_centers(640, 640, 32);
        assert_eq!(centers.len(), 800);
    }

    #[test]
    fn anchor_centers_first_entry_is_half_stride() {
        // First anchor at (0,0) grid cell should be at (stride/2, stride/2)
        let centers = anchor_centers(640, 640, 8);
        let (cx, cy) = centers[0];
        assert!((cx - 4.0).abs() < 1e-5, "cx={cx}");
        assert!((cy - 4.0).abs() < 1e-5, "cy={cy}");
    }

    #[test]
    fn sigmoid_values() {
        assert!((sigmoid(0.0) - 0.5).abs() < 1e-5);
        assert!(sigmoid(100.0) > 0.999);
        assert!(sigmoid(-100.0) < 0.001);
    }

    #[test]
    fn iou_identical_boxes_is_one() {
        let a = [0.0_f32, 0.0, 10.0, 10.0];
        assert!((iou(&a, &a) - 1.0).abs() < 1e-5);
    }

    #[test]
    fn iou_non_overlapping_is_zero() {
        let a = [0.0_f32, 0.0, 5.0, 5.0];
        let b = [10.0_f32, 10.0, 20.0, 20.0];
        assert_eq!(iou(&a, &b), 0.0);
    }

    #[test]
    fn nms_removes_duplicate_boxes() {
        let a = DetectedFace {
            bbox: [0.0, 0.0, 10.0, 10.0],
            keypoints: [[0.0; 2]; 5],
            score: 0.9,
        };
        let b = DetectedFace {
            bbox: [0.5, 0.5, 10.5, 10.5],
            keypoints: [[0.0; 2]; 5],
            score: 0.8,
        };
        let kept = nms(vec![a, b], 0.4);
        assert_eq!(kept.len(), 1, "duplicate should be suppressed");
        assert!((kept[0].score - 0.9).abs() < 1e-5);
    }

    #[test]
    #[ignore = "requires det_10g.onnx model file"]
    fn detect_returns_empty_for_blank_frame() {
        // Manual test: load model, run on blank image, expect Ok(vec![])
    }
}
