//! Auth request sent from PAM module → daemon.

use crate::types::{SecurityMode, UserId};
use crate::PROTOCOL_VERSION;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::ZeroizeOnDrop;

/// Authentication request from PAM module to daemon.
///
/// Sent over Unix socket when a user attempts to authenticate.
#[derive(Debug, Clone, Serialize, Deserialize, ZeroizeOnDrop)]
pub struct AuthRequest {
    /// Protocol version for compatibility check.
    #[zeroize(skip)]
    pub version: u32,

    /// Unique session identifier (generated by PAM module).
    #[zeroize(skip)]
    pub session_id: Uuid,

    /// Username to authenticate.
    pub user: UserId,

    /// Security mode for this auth attempt (from user's config).
    #[zeroize(skip)]
    pub mode: SecurityMode,

    /// Maximum time in milliseconds the daemon may take to respond.
    #[zeroize(skip)]
    pub timeout_ms: u32,
}

impl AuthRequest {
    /// Create a new auth request with default timeout (8 seconds).
    #[must_use]
    pub fn new(user: UserId, mode: SecurityMode) -> Self {
        Self {
            version: PROTOCOL_VERSION,
            session_id: Uuid::new_v4(),
            user,
            mode,
            timeout_ms: 8_000,
        }
    }

    /// Set a custom timeout.
    #[must_use]
    pub fn with_timeout_ms(mut self, ms: u32) -> Self {
        self.timeout_ms = ms;
        self
    }
}
